/**
 * All RTSP Headers, although most of these are generally not used
 * @type {{Require: string, CSeq: string, ContentType: string, Server: string, IfModifiedSince: string, ContentLanguage: string, ProxyRequire: string, ContentEncoding: string, Conference: string, Authorization: string, LastModified: string, Bandwidth: string, UserAgent: string, AcceptLanguage: string, Unsupported: string, Speed: string, Accept: string, ContentBase: string, RetryAfter: string, Connection: string, Referer: string, Scale: string, From: string, Public: string, Range: string, Blocksize: string, Date: string, Allow: string, Via: string, ProxyAuthenticate: string, WWWAuthenticate: string, ContentLocation: string, CacheControl: string, ContentLength: string, Expires: string, RTPInfo: string, Transport: string, AcceptEncoding: string, Session: string}}
 */
module.exports = {
    Accept: 'Accept',
    AcceptEncoding: 'Accept-Encoding',
    AcceptLanguage: 'AcceptLanguage',
    Allow: 'Allow',
    Authorization: 'Authorization',
    Bandwidth: 'Bandwidth',
    Blocksize: 'Blocksize',
    CacheControl: 'Cache-Control',
    Conference: 'Conference',
    Connection: 'Connection',
    ContentBase: 'Content-Base',
    ContentEncoding: 'Content-Encoding',
    ContentLanguage: 'Content-Language',
    ContentLength: 'Content-Length',
    ContentLocation: 'Content-Location',
    ContentType: 'Content-Type',
    CSeq: 'CSeq',
    Date: 'Date',
    Expires: 'Expires',
    From: 'From',
    IfModifiedSince: 'If-Modified-Since',
    LastModified: 'Last-Modified',
    ProxyAuthenticate: 'Proxy-Authenticate',
    ProxyRequire: 'ProxyRequire',
    Public: 'Public',
    Range: 'Range',
    Referer: 'Referer',
    Require: 'Require',
    RetryAfter: 'Retry-After',
    RTPInfo: 'RTP-Info',
    Scale: 'Scale',
    Session: 'Session',
    Server: 'Server',
    Speed: 'Speed',
    Transport: 'Transport',
    Unsupported: 'Unsupported',
    UserAgent: 'User-Agent',
    Via: 'Via',
    WWWAuthenticate: 'WWW-Authenticate'
}